nats-io/nats.ex

lib/gnat.ex, test/gnat_test.exs
This is a first cut at supporting #8 
⚠️ Not Handled in this PR
* cleaning up the `sid` => `pid` mapping
* this could eventually end up using a LOT of space in the VM
* handling invalid `sid`s (ie. `Gnat.unsub(pid, "yer mom")`)
* the optional `max_msgs` parameter
I plan on doing ^ stuff in future PRs
/cc @newellista @tallguy-hackett @jjcarstens
=> basic unsub with a test

lib/gnat.ex, lib/gnat/command.ex, test/command_test.exs, test/gnat_test.exs
Getting a little further with #8 
This PR adds support for doing an `UNSUB` with a maximum number of messages. I decided to make the maximum messages be part of an optional 3rd parameter which comes in as a keyword list. This seems to match a common pattern for APIs in the elixir community. Right now this is the only optional parameter to an unsub command in the NATS protocol, but I imagine that could change in the future so I figured modeling it as a keyword list kept things flexible for the future.
I also didn't want to add multiple `handle_call` clauses or private functions to the `gnat.ex` so I decided to extract the formatting of on-the-wire commands into a separate module.
=> Unsub with max msgs

lib/gnat.ex, mix.exs, mix.lock
Building off of #19, this PR starts to set up some documentation for the project. It adds `ex_doc` as a development dependency and adds a doc string for the `Gnat.unsub/3` function which looks like this when it is rendered:
=> Start documentation

lib/gnat.ex, lib/gnat/command.ex, lib/gnat/parser.ex, test/command_test.exs, test/gnat/parser_test.exs, test/gnat_test.exs
Support for passing a `reply_to` and receiving messages with a `reply_to` value. This is a pre-requisite for #10
In order to support this I needed to change the format of how we deliver messages to subscribed processes. Instead of passing another element in a tuple (I always forget which order the items are in) I changed it to passing a map so you can pattern match in a more readable way.
This is a YOLO breaking change, but we haven't even published to hex.pm so :man_shrugging: :woman_shrugging: 
/cc @newellista @quixoten @film42 @tallguy-hackett
=> Pub with reply

bench.exs, config/config.exs, lib/gnat.ex, test/gnat_test.exs
This introduces a helper function to make doing [request and reply](http://nats.io/documentation/concepts/nats-req-rep/) patterns easier and more efficient (ie by sending the sub, unsub and pub messages together in the same TCP packet).
I also updated the benchmark script and I currently get these numbers on my machine:
```
$ mix run bench.exs
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.4.1
Benchmark suite executing with the following configuration:
warmup: 2.0s
time: 10.0s
parallel: 1
inputs: none specified
Estimated total run time: 48.0s
Benchmarking parse-128...
Benchmarking pub - 128...
Benchmarking req-reply-16...
Benchmarking sub-unsub-pub-16...
Name                       ips        average  deviation …
```
=> Request reply

lib/gnat.ex, lib/gnat/parser.ex, test/gnat/parser_test.exs
This is my attempt at addressing Issue #18 with case insensitivity while parsing.  I split out some of the message parsing so that the case insensitivity check could work in the `cond` call and renamed a function to more appropriately describe parsing a (NATS) command.
I tried to find some kind of magic voodoo what would allow matching against a regex during a pattern match.  There wasn't anything really good.  The closest I found was using something a lot more complicated than I wanted to get into.  So I settled on using a `cond` to allow for regex match on the command name.
=> Case insensitive commands

lib/gnat.ex, lib/gnat/command.ex, test/command_test.exs, test/gnat_test.exs
Adds `SUB` formatting in the `Gnat.Command` module including support for `queue_group`. I also added documentation for subscribing and a test to make sure that we fanout messages in some cases and partition messages when queue group is provided.
/cc @newellista @film42 @tallguy-hackett
=> Sub (with support for queue groups)

lib/gnat/parser.ex, test/gnat/parser_test.exs
A rough cut at #5
I stole the basic idea here from @newellista who suggested that we only really need to keep the unmatched bytes around for the parser state (no need to have a `state: :waiting` etc). This ends up introducing a few more conditionals which always degrades the readability a bit.
Before I try to refactor I first wanted to get some feedback on whether this looked like a reasonable attempt at parsing.
Benchmarks before and after the change show no significant change in performance (~`81k` parses/sec).
/cc @newellista @tallguy-hackett
=> Partial parse

test/gnat_test.exs, test/test_helper.exs
In `test_helper.exs`, ensure that `gnatsd` is running before starting
the test run.
Also, add tag that will exclude any tests that have the `@tag: pending`
tag.
=> Add some test helpers

lib/gnat.ex, test/gnat_test.exs
Fixes #32 
The basic idea here is that we track both a `recipient` pid and a `unsub_after` count for each subscription. If we receive an `unsub` with no max messages we cleanup the subscription immediately after sending the UNSUB command to gnats. If we receive an `unsub` with max messages then we tag the subscription with a number of messages to wait for.
Each time we receive a message and deliver it we decrement the amount remaining and we clean it up when the counter reaches 0.
I tested this by opening `observer` and doing 2MM `Gnat.request` calls. My gnat connection process did not grow in memory. I could see that it's state only ever contained 1 subscription entry and it cleaned up all of the rest of them as responses were received.
/cc @newellista @film42 @jjcarstens …
=> Cleanup subscriptions

.travis.yml, README.md, lib/gnat.ex, lib/gnat/parser.ex, mix.exs, mix.lock, test/gnat/parser_test.exs, test/gnat_test.exs, test/test_helper.exs
This fixes #27 
I added functionality to pass connection information into the parser to generate the `CONNECT` command.  This may not be the best way to do it so I'm very open to suggestions.  I also added a `Gnat.ping` function that sends a `PING` command to the server to help verify an authenticated connection without a need for a subscription request.
There's also no error handling if the client tries to use a connection without authenticating.
=> Auth required

lib/gnat.ex, lib/gnat/handshake.ex
While working on #37 I was bugged by the fact that we had several functions in the `Gnat` module that were only useful for the handshake. I thought it would be nicer to let all of the handshake logic happen in its own module with just a simple `{:ok, socket}` or `{:error, reason}` return value.
I also didn't like constantly having to to do
```elixir
socket_write(state.connection_settings, state.socket, "PING\r\n")
```
So I changed the `socket_write` and `socket_close` functions to just accept the entire state as the first argument and it extracts the options/socket as needed.
```elixir
socket_write(state, "PING\r\n")
```
/cc @quixoten @film42 @newellista @jjcarstens @tallguy-hackett
=> Handshake refactor

.travis.yml, lib/gnat.ex, test/gnat_test.exs, test/test_helper.exs
💥 💥 💥 💥 💥 💥 
I wrote a failing test assuming that I would have to fix it with implementation code, but since we already allow passing in of the `ssl_opts`, this turned out to just be a matter of passing in connection options.
I went ahead and documented some of the connection options and this documentation looks like this when rendered:
/cc @film42 @newellista @jjcarstens @quixoten @tallguy-hackett
=> Client cert

lib/gnat.ex
allow gen server options to be passed to `Gnat` for things like registered names. This is useful for having a supervised nats connection with a registered name. I'm using this in my application at work so that I can pass the registered name as the first argument to `Gnat.sub`, `Gnat.pub`, etc.
Also updated the documentation.
/cc @jjcarstens @newellista @film42 @tallguy-hackett
=> GenServer opts

lib/gnat.ex
Add some error handling.
GenServer should be stopped when server is down.
this may conflict the concept of #42. But I like simple client;)
=> Handle various tcp error

lib/gnat.ex, lib/gnat/parser.ex, test/gnat/parser_test.exs, test/gnat_test.exs
Basic support for `-ERR` messages coming from the broker (see #41)
This PR adds support for parsing the messages from the broker and forwarding them to the [error_logger](http://erlang.org/doc/man/error_logger.html) which is the standard OTP mechanism for error reports, crash reports etc. It is a pluggable system so I'm thinking it will be possible for people to hook up honeybadger or other error monitoring solutions to report these errors.
/cc @film42 @newellista @tallguy-hackett @jjcarstens
=> Handle errors

lib/gnat.ex, lib/gnat/handshake.ex, mix.lock, test/gnat_test.exs
This adds support for a configurable connection timeout that defaults to
3 seconds. I also changed the return value in the init function under
error conditions to `{:stop, reason}` from `{:error, reason}`. I think
this is correct because `{:error, reason}` generated:
```
** (EXIT from #PID<0.208.0>) bad return value: {:error, :timeout}
```
I could also not find support for `{:error, _}` in the docs:
https://hexdocs.pm/elixir/GenServer.html#c:init/1
This was tricky to test because calling `Gnat.start_link` killed the
test immediately. Hopefully calling `Gnat.init` instead is a viable way
to test the behavior.
---
@mmmries @film42 @newellista @tallguy-hackett @jjcarstens
=> Support configurable connection timeout

lib/gnat/connection_supervisor.ex
Addresses #44
This introduces a new module (with docs) that users can put into their supervision tree to get an automatically reconnecting `Gnat` connection. They can pass it a list of locations they want to connect to and let it roll.
/cc @newellista @tallguy-hackett @jjcarstens @film42 @quixoten
=> Supervised connection

lib/gnat.ex
subscription information is not deleted when calling ```Gnat.unsub(state, sid)``` (without max_messages).
=> cleanup state after unsub

lib/gnat.ex
Add checking existence of receiver because calling publish & unsubscribe at the same time might cause receiving message for deleted receiver.
=> Ensure receiver exists before delivering message

lib/gnat/connection_supervisor.ex, lib/gnat/consumer_supervisor.ex
This is a first cut at having supervised consumers. This feature can be used to support things like RPC servers where a client application wants to have long-lived subscriptions that last across re-connect attempts. It works by adding an entry to your supervision tree like:
```elixir
consumer_settings = %{
connection_name: :rpc_gnat,
consuming_function: {Dispatch.RpcServer, :handle_request},
subscription_topics: [
%{topic: "rpc.atlas.dispatch.shard_service.search", queue_group: "rpc.atlas.dispatch.shard_service.search"},
%{topic: "rpc.atlas.dispatch.user_shard_service.search", queue_group: "rpc.atlas.dispatch.user_shard_service.search"},
],
}
children = [worker(Gnat.ConsumerSupervisor, [settings, [name: :rpc_consumer]], shutdown: 30_000)]
supervise(children, strategy: :one_for_one)
``` …
=> Supervised consumers

lib/gnat.ex, lib/gnat/connection_supervisor.ex, lib/gnat/consumer_supervisor.ex
This is the followup to #59 
[Diff link to view diff since #59](https://github.com/mmmries/gnat/compare/supervised_consumers...supervised_consumers_followup)
It adds some documentation and a graceful shutdown mechanism that attempts to unsubscribe and allow some time for messages to finish arriving and processing. The timeout is controlled via the supervision tree (ie `worker(Gnat.ConsumerSupervisor, [settings], shutdown: 30_000)` gives a 30second grace period for the consumer to finish processing before it will be forcibly killed.
I tested it locally with a bunch of extra logging to make sure that all messages were being processed.
/cc @abrandoned @newellista @film42 @quixoten
=> Supervised consumers followup

bench.exs, lib/gnat.ex, lib/gnat/handshake.ex
This follows the pattern in #61, but follows the same pattern for accepting data from the gnats brokers. This gives us ~50% increase in throughput on a [realistic benchmark](https://gist.github.com/mmmries/cf86af5149524155fc2eac3df4a9d948) that sends 128byte requests and gets back 1.3kb responses.
I've also added a `:gnat` key to the messages that get delivered so that client applications can easily setup multiple connections and send back a reply based on the data in the message they received. (ie they don't need to track the name or pid of a connection)
/cc @newellista @film42
=> Optimize Throughput

lib/gnat/consumer_supervisor.ex
Fixes #67 
/cc @film42 @quixoten @newellista
=> handle an EXIT message from the task supervisor

lib/gnat/parser.ex, test/gnat/parser_property_test.exs, test/support/generators.ex
Adds another 2 property tests for the parser that will randomly generate all kinds of protocol messages (`PING`,`PONG`,`+OK`,`-ERR...` and `MSG...`). One test feeds these protocol messages into the parser one at a time, the other test glues them together into one big string and then randomly chunks them up to make sure that we can parse them with any arbitrary byte splitting that might happen at the networking level.
=> add support for parsing +OK messages and property tests

lib/gnat.ex, test/gnat_property_test.exs, test/test_helper.exs
This adds 4 additional property tests that exercise the full library.
* publishes tons of random messages to randomly subjects
* subscribe, publish, receive and unsub from a bunch of random subjects
* perform a bunch of request-reply cycles against an echo server (setup in the `test_helper.exs`)
* test subscribe/unsubscribe with a random max message and then make sure that we receive the expected number of publishes before the subscription dissapears
While adding these tests I also added a `Gnat.active_subscriptions/1` to check the number of subscriptions the connection currently knows about and also made the `receive_additional_tcp_data` into a private function.
=> Property test gnat connection

lib/gnat.ex, test/gnat_property_test.exs, test/gnat_test.exs
This is a rebase of #69
This code is now being exercised the property tests introduced in.
@film42 was the ideas of `sub + :as_request` to enable custom request/reply flows like the one that MX uses? If so, I might take a stab at an alternate method to enabling those without using the `sub` function. Just want to make sure I understand before suggesting any changes.
=> Single request sub

.travis.yml, mix.exs, test/gnat_test.exs
Drop support for Elixir `1.4.X` and OTP `18.X`. We'll test against the latest Elixir 1.5, 1.6 and 1.7 releases and the latest minor versions of OTP 19, 20 and 21.
=> require elixir 1.5+, test on last 3 major release of elixir and OTP

lib/gnat.ex, mix.exs, mix.lock
@entone this is an alternative to you wrapping the `gnat` library. It should allow you to run something like:
* `Telemetry.attach("record_pubs", [:gnat, :pub], Publish, :instrument, nil)`
* `Telemetry.attach("record_subs", [:gnat, :sub], Subscription, :instrument, nil)`
* `Telemetry.attach("record_requests", [:gnat, :request], Request, :instrument, nil)`
* `Telemetry.attach("record_messages", [:gnat, :message_received], Message, :instrument, nil)`
* `Telemetry.attach("record_unsubs", [:gnat, :unsub], Unsubscribe, :instrument, nil)`
Would that give you all the instrumentation you need? Each of the events have metadata about the `topic` except for the `[:gnat, :unsub]` event because we only have the `sid`.  I also ran the benchmarks script before and after these changes and there was no …
=> add telemetry to the project

lib/gnat.ex
Missing `pid` on `request` docs
=> fix: request docs

lib/gnat.ex, mix.exs, mix.lock
Updates telemetry to newest version and removes warnings about deprecated execute/3 with an int 2ng arg. Now uses maps instead
=> updates to telemetry 0.4

README.md, lib/gnat.ex, test/gnat_property_test.exs
Builds off of #86
Mostly just some updates to the README, I also changed the measurements for the `message_received` event to be a `count` instead of a `latency`. I'm trying to avoid the flakey auto-unub tests by giving 10ms for the server to finish registering our subscription before we start publishing messages.
=> report count measurement, and update README

README.md, lib/gnat/connection_supervisor.ex, lib/gnat/consumer_supervisor.ex, mix.exs
This addresses #94 
It documents the `ConnectionSupervisor` and `ConsumerSupervisor` as officially supported (they've been in production for multiple years now) and also bumps the library version to 1.0.0 since it's been stable for a while now.
Thanks @darrenclark for poking the project a little on this 🎉 🎈 💚 💙
=> Official supervisor support

lib/gnat/consumer_supervisor.ex
In the case that a `Gnat.ConsumerSupervisor` is configured without an explicit queue group, a `nil` queue group gets passed to `Command.build(:sub, topic, sid, opts)` on line 246 in `gnat.ex`.
```
children = [
%{
id: :gnat_conn,
start: {
Gnat.ConnectionSupervisor,
:start_link,
[config_nats_conn()]
},
type: :supervisor
},
%{
id: :gnat_sub,
start: {
Gnat.ConsumerSupervisor,
:start_link,
[config_nats_sub()]
},
type: :supervisor
},
]
opts = [
strategy: :one_for_one
]
Supervisor.start_link(children, opts)
```
```
defp config_nats_conn do
nats_host = System.get_env("NATS_HOST", "localhost")
{nats_port, _} = Integer.parse(System.get_env("NATS_PORT", "4222"))
%{
name: :gnat,
backoff_period: 5_000,
connection_settings: [
%{host: nats_host, port: nats_port}
]
}
end
defp config_nats_sub do …
```
=> fix Gnat.ConsumerSupervisor crash when no queue group is specified

README.md
This was just something I noticed when trying to add this package. Hope it helps :) If not feel free to close it.
Currently a user has to look up hexdocs by going to hexdoc and looking for gnat. The repo is called nats.ex so this might be a little misleading.
This commit adds both a badge displaying the current version (with a link to docs) and an explicit box to show the link to hexdocs.
=> docs: add hex badge and link to hexdocs

README.md, lib/gnat.ex, mix.exs
This PR is small, but accomplishes several small improvements.
* fix typo in README that was referencing the old `gnatsd`
* add a typespec for a `Gnat` connection. This way other functions can reference a `Gnat.t()` rather than the generic `GenServer.server()` type (useful for the early work in https://github.com/mmmries/jetstream)
* add a deprecation notice to the `Gnat.ping` function. This function has known race conditions and I would like to hide it from the public interface so that pinging is handled internally
=> update typespecs and a README typo

lib/gnat/connection_supervisor.ex
Currently the ConnectionSupervisor will print out all inputs as part of Logger info. This can lead to unintended leaking of credentials into std.out
Closes #104
=> change log from info to debug when connecting to NATS

CHANGELOG.md
As pointed out in #109 the CHANGELOG was very out-of-date. I went back through the commit history and wrote up notes about what was changed at each minor version change.
=> backfill the last several versions of CHANGELOG

bench/request_multi.exs, lib/gnat.ex, test/gnat_test.exs
This addresses https://github.com/nats-io/nats.ex/issues/117
@autodidaddict can you take a look and see if this looks useful for your situation? I ended up adding in both `receive_timeout` and `max_messages`. Some quick benchmarking shows that doing a `request_multi(gnat, topic, message, max_messages: 1)` has the same level of performance as the normal `request/4` function (~16k request/second single threaded on my laptop).
=> Request multi

lib/gnat.ex, test/gnat_test.exs
This PR adds an ability to customize the hardcoded `_INBOX.` prefix used in some subjects.
In our system, applications get third party JWT tokens allow operating only on specified topics (allow specifier looks usually like this: `app_name.environment.>`). This little option would allow us to use Gnat in such conditions.
I have no idea how to reliably test this parameter, hence no tests are added. If you have any clever ideas, let me know and I can implement these.
=> Allow setting custom inbox prefix

lib/gnat.ex, lib/gnat/handshake.ex, test/gnat_test.exs
Addresses https://github.com/nats-io/nats.ex/issues/123
Includes information about the NATS server that can be accessed from a connection.
=> Server info in connection state

lib/gnat/parsec.ex, test/gnat/parsec_test.exs
This fixes the bug from #122
I got the parsec working correctly here, but I think we should also return the status code and/or description back to the recipient. This PR currently throws that data away, but especially in the case of the pull request with no wait, it seems very useful to let the caller know that we got back a 404 vs a 503 or some other status code.
=> parse hmsg with status code and description

.circleci/config.yml, lib/gnat.ex, test/gnat_test.exs
Adresses #129 
We do support IPv6 already, but it wasn't very clear in the documentation. So this adds a function doc and a unit test.
=> Add a test and some documentation for IPv6 support

README.md, lib/gnat.ex, lib/gnat/handshake.ex, lib/gnat/parsec.ex, test/gnat/parsec_test.exs, test/gnat_test.exs
Resolves #136 
The NATS server has the ability to send reply messages with a status of `503` when a message is sent to a topic with no subscribers. This is really handy for request-reply semantics so you can get an immediate error response rather than waiting for the `receive_timeout` to expire. Because this behavior is backwards incompatible, it must be opted into by the client.
I've written this PR assuming that we also want our users to opt into this behavior rather than making it the default, but I'm open to feedback on this point. Maybe we should default the `no_responders: true` after the next major version release?
If headers are enabled, and the user has passed in `no_responders: true` with their connection options, then the server will send back HMSG payloads with an empty body …
=> No responders

.circleci/config.yml
The test suite for this library is tested on the latest elixir versions from 1.7 => 1.13. Time for us to add elixir 1.14 to the test matrix so we can confirm support for erlang 25 and elixir 1.14
=> include elixir 1.14.2 in the test matrix

.circleci/config.yml, MAINTAINERS.md, README.md, lib/gnat.ex, lib/gnat/consumer_supervisor.ex, lib/gnat/services/server.ex, lib/gnat/services/service_responder.ex, lib/gnat/services/wire_protocol.ex, mix.exs, test/gnat/consumer_supervisor_test.exs, test/test_helper.exs
* Adds support for creating microservices - developer experience is nearly identical to regular `Gnat.Server`
* automatically adds responder for ping, stats, and info
* Fills out a few of the sparse areas of documentation
* Fixes some broken links in the docs
* Adds service request and service error to telemetry 
It's been a while since I've written some Elixir so apologies in advance if I've dumped a bunch of non-idiomatic code in this PR
=> Adding initial services API support

lib/gnat/jetstream/api/kv.ex, lib/gnat/jetstream/api/stream.ex, test/jetstream/api/kv_test.exs
Addresses #152 
```elixir
{:ok, conn} = Gnat.start_link()
Gnat.Jetstream.API.KV.list_buckets(conn)
```
=> Added a function to list available buckets

.github/workflows/CI.yml, test/gnat/consumer_supervisor_test.exs, test/jetstream/api/stream_test.exs
While reviewing #152 I ran across a few cases where CI produced flakey results. This PR handles some of the race conditions to make the test suite more dependable.
=> Avoid flakey tests

lib/gnat/jetstream/api/stream.ex
After merging #152 I ran into a couple of failed CI runs [like this](https://github.com/nats-io/nats.ex/actions/runs/8717193784/job/23947157335)
It turns out that the jetstream API sometimes returns `"streams": null` in their JSON response when there are no streams defined. This means that we end up getting back a `nil` value rather than a list. This would require client code to handle nils rather than being able to always treat the return as a possible-empty list.
This PR smooths over the rough edge to make sure we always return the list of streams as a list
=> treat no streams as an empty list

lib/gnat.ex, lib/gnat/jetstream/jetstream.ex, lib/gnat/jetstream/pager.ex, test/jetstream/pager_test.exs
I did a bit of experimenting with having a functionality interface for a pull consumer that I think might be useful for people. The basic idea is that the caller calls `Pager.init(...)` and then repeatedly calls `Pager.page` to get the next "page" of messages. When the `page` function returns `{:done, messages}` it means the consumer has reached the current end of the stream and the client should then call `Pager.cleanup` to immediately cleanup the subscription and consumer.
=> Page over stream

lib/gnat/jetstream/api/stream.ex
When updating a stream that has `allow_direct` stream set to `true` will overwrite it within the server to `false`. It was a rather unexpected behavior. If there is a better way to implement this, please let me know. Thanks!
=> fix: add stream fields `allow_direct` and `mirror_direct`

lib/gnat/jetstream/api/stream.ex, test/jetstream/api/stream_test.exs
This PR adds the support for the `discard_new_per_subject` field to the `Stream` structure.
=> Add stream field discard_new_per_subject

lib/gnat/jetstream/api/object.ex, test/jetstream/api/object_test.exs
This PR closes #168 and adds the ability to list Object bucket streams, replicating the nats CLI command `nats object ls`.
Credit to @lsxliron as this PR is based off of their PR to add the `list_buckets` function to the KV API.
=> Add list_buckets function and tests to Object API

README.md, lib/gnat.ex
Single quotes (charlists) were used instead of double quotes (binaries).
=> Fix incorrect useage of charlist

lib/gnat/jetstream/api/kv.ex
the `is_` prefix is [reserved for guards](https://hexdocs.pm/elixir/1.18.1/naming-conventions.html#is_-prefix-is_foo) by convention. This PR aligns the function name with the convention for [functions that return booleans](https://hexdocs.pm/elixir/1.18.1/naming-conventions.html#trailing-question-mark-foo)
=> Soft deprecate is_kv_bucket_stream?/1 in favor of kv_bucket_stream?/1

README.md
This tripped me up a bit and took me a while to realize how NATS works with no authentication. I would like to follow up with a Docker compose setup that explicitly creates the necessary configuration.
=> Clarify authentication setup during test

lib/gnat/jetstream/api/kv.ex, test/jetstream/api/kv_test.exs
Adds a convenience function for getting info of buckets.
As a note, I think that `Stream.info/3` should be changed to take a keyword list. We can support the case where its nil/binary still
=> Gnat.Jetstream.API.KV.info/3

lib/gnat/jetstream/pull_consumer/connection_options.ex
Gnat already requires Elixir 1.14, so we're safe to remove
=> Remove function_exported? check for Keyword.validate!/2

lib/gnat/jetstream/api/kv.ex
Removes the unnecessary flat map. The performance difference should be pretty small (tbh I didn't measure), but slightly faster and less memory.
=> Tiny optimization to KV.list_buckets/1

lib/gnat/jetstream/api/kv/watcher.ex, test/jetstream/api/kv_test.exs
When creating keys (or updating) with the `{"nats-expected-last-subject-sequence", "<seq>"}` header, KV watcher did not trigger the handler.
=> make KV-watcher emit `:key_added` events when the message has a header

lib/gnat/jetstream/api/stream.ex
I noticed a lot of warnings in the local nats server when running `mix test`:
```
[1] 2025/06/15 08:30:08.523129 [WRN] 172.17.0.1:58290 - cid:886 - Invalid JetStream request '$G > $JS.API.STREAM.CREATE.pager_a': json: unknown field "domain"
[1] 2025/06/15 08:30:09.385284 [WRN] 172.17.0.1:52226 - cid:895 - Invalid JetStream request '$G > $JS.API.STREAM.CREATE.astream': json: unknown field "domain"
[1] 2025/06/15 08:30:09.467124 [WRN] 172.17.0.1:52324 - cid:911 - Invalid JetStream request '$G > $JS.API.STREAM.CREATE.delstream': json: unknown field "domain"
[1] 2025/06/15 08:30:09.475414 [WRN] 172.17.0.1:52348 - cid:916 - Invalid JetStream request '$G > $JS.API.STREAM.CREATE.anewstream': json: unknown field "domain"
[1] 2025/06/15 08:30:09.479769 [WRN] 172.17.0.1:52364 - cid:920 - Invalid …
```
=> fix: unknown field domain in Stream.create

lib/gnat/jetstream/api/consumer.ex
When trying to query an existing consumer with a deliver policy of `by_start_time`, this error occurs:
```** (ArgumentError) errors were found at the given arguments:
* 1st argument: not an already existing atom
:erlang.binary_to_existing_atom("by_start_time")
(gnat 1.10.0) lib/gnat/jetstream/api/consumer.ex:453: Gnat.Jetstream.API.Consumer.to_config/1
(gnat 1.10.0) lib/gnat/jetstream/api/consumer.ex:482: Gnat.Jetstream.API.Consumer.to_info/1
(gnat 1.10.0) lib/gnat/jetstream/api/consumer.ex:301: Gnat.Jetstream.API.Consumer.info/4
```
This PR fixes the issue by extending the consumer validation to include checks on the `deliver_policy` (and `replay_policy`). Because the atoms are now included in the compiled modules the error is resolved.
=> Fix deliver policy

.formatter.exs, lib/gnat/jetstream/api/kv.ex
This PR does the following:
- Includes Elixir modules and scripts in formatter configuration, allowing extensions using Elixir Dialyzer/LSP for autoformatting to find Elixir scripts and modules in a given context/directory
- Updates the type spec for KV's opts to implicit `keyword` while hinting at the potential option for configuring 
the request's `timeout`
=> Hint `:timeout` option in KV's typespec

lib/gnat.ex
Fixes #51 
This PR implements a regularly scheduled PING/PONG health check. By default we will run this every 10sec (configurable by the user via the `ping_interval` option). After a successful handhake, we will send a `PING` at each interval and we set a state of `waiting_on_pong: true`. This state is cleared whenever we receive a `PONG` from the server (in my testing with a local NATS server, this always came back in less than 1ms).
If we get to the next ping interval and we are still waiting on a PONG, we crash the process with an error message about not having received a PONG.
=> implement regularly scheduled PING/PONG health check

.github/workflows/CI.yml
Based on https://github.com/nats-io/nats.ex/security/code-scanning/2
=> specify minimal CI permissions
